laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('busca', 'BuscaController@index')->name('busca');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('quem-somos', 'QuemSomosController@index')->name('quemSomos');
    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('catalogo', 'CatalogoController@index')->name('catalogo');
    Route::get('catalogo/{produto}', 'CatalogoController@show')->name('catalogo.show');
    Route::get('catalogo-pdf', 'CatalogoController@pdf')->name('catalogoPdf');
    Route::get('novidades/{novidades_categoria?}', 'NovidadesController@index')->name('novidades');
    Route::get('novidades/{novidades_categoria}/{novidade}', 'NovidadesController@show')->name('novidades.show');
    Route::get('qualidade', 'QualidadeController@index')->name('qualidade');
    Route::get('representantes', 'RepresentantesController@index')->name('representantes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('quem-somos/textos', 'QuemSomosTextosController', ['parameters' => ['textos' => 'quem-somos_textos']]);
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
        Route::resource('produtos/equivalencia', 'ProdutosEquivalenciaController', ['except' => ['edit', 'update']]);
		Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::resource('produtos.veiculos', 'ProdutosVeiculosController');
		Route::resource('produtos-texto', 'ProdutosTextoController', ['only' => ['index', 'update']]);
		Route::resource('novidades/categorias', 'NovidadesCategoriasController', ['parameters' => ['categorias' => 'categorias_novidades']]);
		Route::resource('novidades', 'NovidadesController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::get('banners/{banners}/remover-imagem/{key}', 'BannersController@removerImagem')->name('painel.banners.removerImagem');
		Route::resource('banners', 'BannersController');
		Route::resource('catalogo-pdf', 'CatalogoPdfController', ['only' => ['index', 'update']]);
		Route::resource('certificacoes', 'CertificacoesController');
		Route::resource('qualidade', 'QualidadeController', ['only' => ['index', 'update']]);
		Route::resource('representantes', 'RepresentantesController');
		Route::resource('representantes.cadastros', 'RepresentantesCadastrosController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('newsletter', 'NewsletterController', ['only' => ['index', 'destroy']]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')->name('painel.newsletter.exportar');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('importacao', 'ImportacaoController@index')->name('painel.importacao');
        Route::post('importacao/produtos', 'ImportacaoController@produtos')->name('painel.importacao.produtos');
        Route::post('importacao/veiculos', 'ImportacaoController@veiculos')->name('painel.importacao.veiculos');
        Route::post('importacao/equivalencia', 'ImportacaoController@equivalencia')->name('painel.importacao.equivalencia');
        Route::get('importacao/imagens', 'ImportacaoController@imagens')->name('painel.importacao.imagens');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Produto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;

class Produto extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'produtos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('titulo', 'ASC');
    }

    public function scopeCategoria($query, $categoria_id)
    {
        return $query->where('produtos_categoria_id', $categoria_id);
    }

    public function categoria()
    {
        return $this->belongsTo('App\Models\ProdutoCategoria', 'produtos_categoria_id');
    }

    public function equivalencias()
    {
        return $this->hasMany(ProdutoEquivalencia::class, 'produto_id');
    }

    public function veiculos()
    {
        return $this->hasMany(ProdutoVeiculo::class, 'produto_id')->ordenados();
    }

    public function getTituloPainelAttribute()
    {
        $titulo  = '';
        $titulo .= $this->categoria ? $this->categoria->titulo : 'sem categoria';
        $titulo .= ' | '.$this->titulo.' - ';
        $titulo .= 'código GAP: '.$this->codigo_gap.' - ';
        $titulo .= 'número original: '.str_replace(['<br>', '<br/>', '<br />'], [',', ',', ','], $this->numero_original);

        return $titulo;
    }

    public static function upload_imagem()
    {
        return CropImage::make('imagem', [
            [
                'width'  => 500,
                'height' => 500,
                'path'   => 'assets/img/produtos/',
                'upsize' => true,
                'transparent' => true
            ],
            [
                'width'  => 280,
                'height' => 280,
                'path'   => 'assets/img/produtos/thumbs/',
                'upsize' => true,
                'transparent' => true
            ]
        ]);
    }
}

laravel/app/Http/Controllers/Painel/ProdutosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ProdutosRequest;
use App\Http\Controllers\Controller;

use App\Models\Produto;
use App\Models\ProdutoCategoria;

class ProdutosController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = ProdutoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (ProdutoCategoria::find($filtro)) {
            $registros = Produto::where('produtos_categoria_id', $filtro)->ordenados()->get();
        } else {
            $registros = Produto::leftJoin('produtos_categorias as cat', 'cat.id', '=', 'produtos_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('produtos.*')
                ->ordenados()->paginate(15);
        }

        return view('painel.produtos.index', compact('categorias', 'registros', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.produtos.create', compact('categorias'));
    }

    public function store(ProdutosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Produto::upload_imagem();

            Produto::create($input);

            return redirect()->route('painel.produtos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Produto $registro)
    {
        $categorias = $this->categorias;

        return view('painel.produtos.edit', compact('registro', 'categorias'));
    }

    public function update(ProdutosRequest $request, Produto $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Produto::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.produtos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Produto $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.produtos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProdutoCategoria;
use App\Models\ProdutosTexto;

class ProdutosController extends Controller
{
    public function index(ProdutoCategoria $categoria)
    {
        $categorias = ProdutoCategoria::ordenados()->get();

        if ($categoria->exists) {
            return view('frontend.produtos.categoria', compact('categorias', 'categoria'));
        }

        $produtosTexto = ProdutosTexto::first();

        return view('frontend.produtos.index', compact('produtosTexto', 'categorias'));
    }
}

laravel/resources/views/painel/produtos/veiculos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos / {{ $produto->titulo }} /</small> Adicionar Veículo</h2>
    </legend>

    {!! Form::open([
        'route' => ['painel.produtos.veiculos.store', $produto->id],
        'files' => true
    ]) !!}

        @include('painel.produtos.veiculos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/veiculos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos / {{ $produto->titulo }} /</small> Editar Veículo</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.produtos.veiculos.update', $produto->id, $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.produtos.veiculos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/veiculos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('montadora', 'Montadora') !!}
    {!! Form::select('montadora', $montadoras, null, ['class' => 'form-control dropdown-tags', 'placeholder' => 'Selecione ou digite e aperte [Enter]']) !!}
</div>

<div class="form-group">
    {!! Form::label('veiculo', 'Veículo') !!}
    {!! Form::select('veiculo', $veiculos, null, ['class' => 'form-control dropdown-tags', 'placeholder' => 'Selecione ou digite e aperte [Enter]']) !!}
</div>

<div class="well">
    {!! Form::label('ano', 'Ano') !!}
    <div class="form-inline">
        <div class="form-group">
            {!! Form::text('ano_inicial', null, ['class' => 'form-control', 'maxlength' => 4]) !!}
        </div>
        <span style="margin: 0 10px">a</span>
        <div class="form-group">
            {!! Form::text('ano_final', null, ['class' => 'form-control', 'maxlength' => 4]) !!}
        </div>
    </div>
</div>

<div class="form-group">
    {!! Form::label('posicao', 'Posição') !!}
    {!! Form::text('posicao', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('dhm', 'DHM') !!}
    {!! Form::text('dhm', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('lado', 'Lado') !!}
    {!! Form::text('lado', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.veiculos.index', $produto->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/veiculos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.produtos.index') }}" title="Voltar para Produtos" class="btn btn-sm btn-default">
        &larr; Voltar para Produtos    </a>

    <legend>
        <h2>
            <small>Produtos / {{ $produto->titulo }} /</small> Veículos

            <a href="{{ route('painel.produtos.veiculos.create', $produto->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Veículo</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="produtos_veiculos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Montadora / Veículo</th>
                <th>Ano</th>
                <th>Posição</th>
                <th>DHM</th>
                <th>Lado</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>
                    {{ $registro->montadora }} / {{ $registro->veiculo }}
                </td>
                <td>{{ $registro->ano }}</td>
                <td>{{ $registro->posicao }}</td>
                <td>{{ $registro->dhm }}</td>
                <td>{{ $registro->lado }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.produtos.veiculos.destroy', $produto->id, $registro->id), 'method' => 'delete')) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.produtos.veiculos.edit', [$produto->id, $registro->id]) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection