laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('busca', 'BuscaController@index')->name('busca');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('quem-somos', 'QuemSomosController@index')->name('quemSomos');
    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('catalogo', 'CatalogoController@index')->name('catalogo');
    Route::get('catalogo/{produto}', 'CatalogoController@show')->name('catalogo.show');
    Route::get('catalogo-pdf', 'CatalogoController@pdf')->name('catalogoPdf');
    Route::get('novidades/{novidades_categoria?}', 'NovidadesController@index')->name('novidades');
    Route::get('novidades/{novidades_categoria}/{novidade}', 'NovidadesController@show')->name('novidades.show');
    Route::get('qualidade', 'QualidadeController@index')->name('qualidade');
    Route::get('representantes', 'RepresentantesController@index')->name('representantes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('quem-somos/textos', 'QuemSomosTextosController', ['parameters' => ['textos' => 'quem-somos_textos']]);
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
        Route::resource('produtos/equivalencia', 'ProdutosEquivalenciaController', ['except' => ['edit', 'update']]);
		Route::resource('produtos/categorias', 'ProdutosCategoriasController', ['parameters' => ['categorias' => 'categorias_produtos']]);
		Route::resource('produtos', 'ProdutosController');
		Route::resource('produtos.veiculos', 'ProdutosVeiculosController');
		Route::resource('produtos-texto', 'ProdutosTextoController', ['only' => ['index', 'update']]);
		Route::resource('novidades/categorias', 'NovidadesCategoriasController', ['parameters' => ['categorias' => 'categorias_novidades']]);
		Route::resource('novidades', 'NovidadesController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::get('banners/{banners}/remover-imagem/{key}', 'BannersController@removerImagem')->name('painel.banners.removerImagem');
		Route::resource('banners', 'BannersController');
		Route::resource('catalogo-pdf', 'CatalogoPdfController', ['only' => ['index', 'update']]);
		Route::resource('certificacoes', 'CertificacoesController');
		Route::resource('qualidade', 'QualidadeController', ['only' => ['index', 'update']]);
		Route::resource('representantes', 'RepresentantesController');
		Route::resource('representantes.cadastros', 'RepresentantesCadastrosController');
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('newsletter', 'NewsletterController', ['only' => ['index', 'destroy']]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')->name('painel.newsletter.exportar');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('importacao', 'ImportacaoController@index')->name('painel.importacao');
        Route::post('importacao/produtos', 'ImportacaoController@produtos')->name('painel.importacao.produtos');
        Route::post('importacao/veiculos', 'ImportacaoController@veiculos')->name('painel.importacao.veiculos');
        Route::post('importacao/equivalencia', 'ImportacaoController@equivalencia')->name('painel.importacao.equivalencia');
        Route::get('importacao/imagens', 'ImportacaoController@imagens')->name('painel.importacao.imagens');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/QuemSomos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Helpers\CropImage;

class QuemSomos extends Model
{
    protected $table = 'quem_somos';

    protected $guarded = ['id'];

}

laravel/app/Http/Controllers/Painel/QuemSomosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\QuemSomosRequest;
use App\Http\Controllers\Controller;

use App\Models\QuemSomos;

class QuemSomosController extends Controller
{
    public function index()
    {
        $registro = QuemSomos::first();

        return view('painel.quem-somos.edit', compact('registro'));
    }

    public function update(QuemSomosRequest $request, QuemSomos $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.quem-somos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/QuemSomosController.php
<?php

namespace App\Http\Controllers;

use App\Models\QuemSomos;
use App\Models\QuemSomosTexto;

class QuemSomosController extends Controller
{
    public function index()
    {
        $quemSomos = QuemSomos::first();
        $textos    = QuemSomosTexto::ordenados()->get();

        return view('frontend.quem-somos', compact('quemSomos', 'textos'));
    }
}

laravel/resources/views/painel/quem-somos/textos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Quem Somos / Textos /</small> Adicionar Texto</h2>
    </legend>

    {!! Form::open(['route' => 'painel.quem-somos.textos.store', 'files' => true]) !!}

        @include('painel.quem-somos.textos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/quem-somos/textos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Quem Somos / Textos /</small> Editar Texto</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.quem-somos.textos.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.quem-somos.textos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/quem-somos/textos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/quem-somos/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto', 'Texto') !!}
    {!! Form::text('texto', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.quem-somos.textos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/quem-somos/textos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.quem-somos.index') }}" class="btn btn-sm btn-default">&larr; Voltar para Quem Somos</a>

    <legend>
        <h2>
            <small>Quem Somos /</small> Textos
            <a href="{{ route('painel.quem-somos.textos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Texto</a>
        </h2>
    </legend>


    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="quem_somos_textos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.quem-somos.textos.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.quem-somos.textos.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection